[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os
sqlalchemy.url = postgresql+psycopg2://postgres:postgres@postgres:5432/trazio

[post_write_hooks]
[post_write_hooks.hooks]
[post_write_hooks.lint]
