"""Seed 50 Chennai destinations for TRAZIO."""

from sqlalchemy import text

from app.db.session import SessionLocal
from app.models.destination import Destination, DestinationCategory


DESTINATIONS = [
    # Beaches / Nature
    {
        "name": "Marina Beach",
        "slug": "marina-beach",
        "category": "nature",
        "location": "POINT(80.2824 13.0500)",
        "description": "Chennai's iconic urban beach along the Bay of Bengal.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "Open daily",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 120,
        "popularity_score": 98,
    },
    {
        "name": "Elliot's Beach",
        "slug": "elliots-beach",
        "category": "nature",
        "location": "POINT(80.2690 12.9998)",
        "description": "Popular seaside destination in Besant Nagar.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "Open daily",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 90,
        "popularity_score": 92,
    },
    {
        "name": "Besant Nagar Beach",
        "slug": "besant-nagar-beach",
        "category": "nature",
        "location": "POINT(80.2698 13.0007)",
        "description": "Relaxed coastal destination around Besant Nagar.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "Open daily",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 90,
        "popularity_score": 90,
    },
    {
        "name": "Guindy National Park",
        "slug": "guindy-national-park",
        "category": "nature",
        "location": "POINT(80.2395 13.0068)",
        "description": "Urban national park known for its biodiversity and nature trails.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "09:00-17:30",
        "entry_fee": 20,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 120,
        "popularity_score": 88,
    },
    {
        "name": "Adyar Eco Park",
        "slug": "adyar-eco-park",
        "category": "nature",
        "location": "POINT(80.2560 13.0158)",
        "description": "Urban ecological park along the Adyar River.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "09:00-17:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 90,
        "popularity_score": 82,
    },
    {
        "name": "Semmozhi Poonga",
        "slug": "semmozhi-poonga",
        "category": "nature",
        "location": "POINT(80.2507 13.0504)",
        "description": "Botanical garden in central Chennai.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "06:00-20:00",
        "entry_fee": 25,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 90,
        "popularity_score": 80,
    },
    {
        "name": "Arignar Anna Zoological Park",
        "slug": "arignar-anna-zoological-park",
        "category": "nature",
        "location": "POINT(80.0815 12.8797)",
        "description": "Large zoological park at Vandalur.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "09:00-17:30",
        "entry_fee": 200,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 240,
        "popularity_score": 91,
    },
    {
        "name": "Chennai Snake Park",
        "slug": "chennai-snake-park",
        "category": "nature",
        "location": "POINT(80.2398 13.0078)",
        "description": "Wildlife park focused on snakes and reptiles.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "09:00-17:30",
        "entry_fee": 30,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 75,
        "popularity_score": 75,
    },
    {
        "name": "Muttukadu Boat House",
        "slug": "muttukadu-boat-house",
        "category": "entertainment",
        "location": "POINT(80.2452 12.8268)",
        "description": "Popular boating and recreational destination on the ECR.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "09:00-18:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 120,
        "popularity_score": 78,
    },
    {
        "name": "Pulicat Lake",
        "slug": "pulicat-lake",
        "category": "nature",
        "location": "POINT(80.0620 13.4170)",
        "description": "Large brackish lagoon known for birdlife and scenic landscapes.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "Open daily",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 180,
        "popularity_score": 70,
    },

    # Heritage / Culture
    {
        "name": "Fort St. George",
        "slug": "fort-st-george",
        "category": "cultural",
        "location": "POINT(80.2881 13.0795)",
        "description": "Historic British fort and major heritage landmark of Chennai.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "09:00-17:00",
        "entry_fee": 5,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 120,
        "popularity_score": 94,
    },
    {
        "name": "Fort Museum",
        "slug": "fort-museum",
        "category": "cultural",
        "location": "POINT(80.2885 13.0802)",
        "description": "Museum displaying colonial-era artefacts and historical collections.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "09:00-17:00",
        "entry_fee": 5,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 90,
        "popularity_score": 82,
    },
    {
        "name": "St. Mary's Church",
        "slug": "st-marys-church",
        "category": "cultural",
        "location": "POINT(80.2886 13.0808)",
        "description": "Historic Anglican church inside Fort St. George.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "06:00-18:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 45,
        "popularity_score": 78,
    },
    {
        "name": "Government Museum Chennai",
        "slug": "government-museum-chennai",
        "category": "cultural",
        "location": "POINT(80.2608 13.0694)",
        "description": "Major museum complex with archaeological, bronze and art collections.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "09:30-17:30",
        "entry_fee": 15,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 180,
        "popularity_score": 91,
    },
    {
        "name": "Valluvar Kottam",
        "slug": "valluvar-kottam",
        "category": "cultural",
        "location": "POINT(80.2425 13.0520)",
        "description": "Monument dedicated to Tamil poet Thiruvalluvar.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "08:00-18:00",
        "entry_fee": 10,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 75,
        "popularity_score": 88,
    },
    {
        "name": "Vivekananda House",
        "slug": "vivekananda-house",
        "category": "cultural",
        "location": "POINT(80.2785 13.0490)",
        "description": "Historic Ice House associated with Swami Vivekananda.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "10:00-12:30;15:00-19:00",
        "entry_fee": 20,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 75,
        "popularity_score": 79,
    },
    {
        "name": "Chennai Rail Museum",
        "slug": "chennai-rail-museum",
        "category": "cultural",
        "location": "POINT(80.2088 13.0898)",
        "description": "Railway heritage museum featuring locomotives and railway artefacts.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "10:00-17:00",
        "entry_fee": 50,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 120,
        "popularity_score": 77,
    },
    {
        "name": "DakshinaChitra Museum",
        "slug": "dakshinachitra-museum",
        "category": "cultural",
        "location": "POINT(80.2386 12.7940)",
        "description": "Living heritage museum showcasing South Indian architecture and crafts.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "10:00-18:00",
        "entry_fee": 250,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 180,
        "popularity_score": 86,
    },
    {
        "name": "Cholamandal Artists' Village",
        "slug": "cholamandal-artists-village",
        "category": "cultural",
        "location": "POINT(80.2510 12.9472)",
        "description": "Artist community and cultural space on the ECR.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "09:30-18:30",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 120,
        "popularity_score": 79,
    },

    # Temples / Religious landmarks
    {
        "name": "Kapaleeshwarar Temple",
        "slug": "kapaleeshwarar-temple",
        "category": "cultural",
        "location": "POINT(80.2707 13.0339)",
        "description": "Historic Dravidian temple in Mylapore.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "06:00-12:30;16:00-21:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 75,
        "popularity_score": 96,
    },
    {
        "name": "Parthasarathy Temple",
        "slug": "parthasarathy-temple",
        "category": "cultural",
        "location": "POINT(80.2773 13.0538)",
        "description": "Historic Vaishnavite temple in Triplicane.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "06:00-12:00;16:00-21:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 60,
        "popularity_score": 91,
    },
    {
        "name": "Santhome Cathedral Basilica",
        "slug": "santhome-cathedral-basilica",
        "category": "cultural",
        "location": "POINT(80.2785 13.0336)",
        "description": "Historic basilica built over the traditional tomb of Saint Thomas.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "06:00-20:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 60,
        "popularity_score": 90,
    },
    {
        "name": "Kalikambal Kamadeswarar Temple",
        "slug": "kalikambal-kamadeswarar-temple",
        "category": "cultural",
        "location": "POINT(80.2875 13.0940)",
        "description": "Historic temple in the George Town area.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "06:00-12:00;16:00-21:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 60,
        "popularity_score": 78,
    },
    {
        "name": "Vadapalani Murugan Temple",
        "slug": "vadapalani-murugan-temple",
        "category": "cultural",
        "location": "POINT(80.2124 13.0507)",
        "description": "Popular Murugan temple in Vadapalani.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "05:00-12:00;16:00-21:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 60,
        "popularity_score": 86,
    },
    {
        "name": "Ashtalakshmi Temple",
        "slug": "ashtalakshmi-temple",
        "category": "cultural",
        "location": "POINT(80.2716 12.9976)",
        "description": "Temple overlooking the Bay of Bengal in Besant Nagar.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "06:30-12:00;16:00-21:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 60,
        "popularity_score": 84,
    },
    {
        "name": "Thousand Lights Mosque",
        "slug": "thousand-lights-mosque",
        "category": "cultural",
        "location": "POINT(80.2547 13.0534)",
        "description": "Historic mosque and landmark in central Chennai.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "Open daily",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 45,
        "popularity_score": 72,
    },

    # Science / Education
    {
        "name": "BM Birla Planetarium",
        "slug": "bm-birla-planetarium",
        "category": "entertainment",
        "location": "POINT(80.2495 13.0067)",
        "description": "Planetarium featuring astronomy shows and science exhibits.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "10:00-17:45",
        "entry_fee": 30,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 120,
        "popularity_score": 84,
    },
    {
        "name": "Birla Planetarium Science Centre",
        "slug": "birla-science-centre",
        "category": "entertainment",
        "location": "POINT(80.2501 13.0070)",
        "description": "Science exhibition and educational complex near the planetarium.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "10:00-17:30",
        "entry_fee": 20,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 90,
        "popularity_score": 72,
    },

    # Parks / Family
    {
        "name": "Guindy Children's Park",
        "slug": "guindy-childrens-park",
        "category": "entertainment",
        "location": "POINT(80.2408 13.0037)",
        "description": "Family-oriented park adjacent to Guindy National Park.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "09:00-17:30",
        "entry_fee": 20,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 90,
        "popularity_score": 73,
    },
    {
        "name": "Nageswara Rao Park",
        "slug": "nageswara-rao-park",
        "category": "nature",
        "location": "POINT(80.2622 13.0315)",
        "description": "Neighbourhood green space in Mylapore.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "06:00-21:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 60,
        "popularity_score": 68,
    },
    {
        "name": "Tower Park Anna Nagar",
        "slug": "tower-park-anna-nagar",
        "category": "nature",
        "location": "POINT(80.2205 13.0878)",
        "description": "Popular urban park surrounding Anna Nagar Tower.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "06:00-21:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 60,
        "popularity_score": 70,
    },

    # Shopping
    {
        "name": "Pondy Bazaar",
        "slug": "pondy-bazaar",
        "category": "shopping",
        "location": "POINT(80.2342 13.0418)",
        "description": "Busy shopping district in T. Nagar.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "10:00-22:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 120,
        "popularity_score": 91,
    },
    {
        "name": "T Nagar Shopping District",
        "slug": "t-nagar-shopping-district",
        "category": "shopping",
        "location": "POINT(80.2340 13.0410)",
        "description": "Major shopping destination known for textiles, jewellery and retail.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "10:00-22:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 150,
        "popularity_score": 95,
    },
    {
        "name": "Express Avenue",
        "slug": "express-avenue",
        "category": "shopping",
        "location": "POINT(80.2618 13.0585)",
        "description": "Large shopping and entertainment complex in Royapettah.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "10:00-22:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 150,
        "popularity_score": 87,
    },
    {
        "name": "Phoenix Marketcity Chennai",
        "slug": "phoenix-marketcity-chennai",
        "category": "shopping",
        "location": "POINT(80.2017 12.9925)",
        "description": "Large modern shopping mall with retail, dining and entertainment.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "10:00-22:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 180,
        "popularity_score": 89,
    },
    {
        "name": "Spencer Plaza",
        "slug": "spencer-plaza",
        "category": "shopping",
        "location": "POINT(80.2580 13.0618)",
        "description": "Historic shopping complex on Anna Salai.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "10:00-21:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 120,
        "popularity_score": 75,
    },

    # Entertainment
    {
        "name": "MGM Dizzee World",
        "slug": "mgm-dizzee-world",
        "category": "entertainment",
        "location": "POINT(80.2448 12.7758)",
        "description": "Amusement and water park on East Coast Road.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "10:30-18:30",
        "entry_fee": 699,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 300,
        "popularity_score": 80,
    },
    {
        "name": "VGP Universal Kingdom",
        "slug": "vgp-universal-kingdom",
        "category": "entertainment",
        "location": "POINT(80.2528 12.9118)",
        "description": "Amusement park and entertainment destination on ECR.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "11:00-19:30",
        "entry_fee": 550,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 240,
        "popularity_score": 78,
    },
    {
        "name": "Madras Crocodile Bank",
        "slug": "madras-crocodile-bank",
        "category": "nature",
        "location": "POINT(80.2418 12.7584)",
        "description": "Reptile conservation centre on the East Coast Road.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "09:00-17:30",
        "entry_fee": 200,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 150,
        "popularity_score": 84,
    },
    {
        "name": "Dakshinachitra Craft Village",
        "slug": "dakshinachitra-craft-village",
        "category": "cultural",
        "location": "POINT(80.2389 12.7942)",
        "description": "Traditional craft and heritage experience near Muttukadu.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "10:00-18:00",
        "entry_fee": 250,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 150,
        "popularity_score": 80,
    },

    # Historic / civic landmarks
    {
        "name": "MGR Memorial",
        "slug": "mgr-memorial",
        "category": "cultural",
        "location": "POINT(80.2830 13.0645)",
        "description": "Memorial complex on the Marina waterfront.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "06:00-21:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 60,
        "popularity_score": 89,
    },
    {
        "name": "Anna Memorial",
        "slug": "anna-memorial",
        "category": "cultural",
        "location": "POINT(80.2820 13.0640)",
        "description": "Memorial dedicated to C. N. Annadurai near Marina Beach.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "06:00-21:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 45,
        "popularity_score": 85,
    },
    {
        "name": "Victory War Memorial",
        "slug": "victory-war-memorial",
        "category": "cultural",
        "location": "POINT(80.2885 13.0728)",
        "description": "War memorial near the Marina and Fort area.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "Open daily",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 45,
        "popularity_score": 70,
    },
    {
        "name": "Gandhi Mandapam",
        "slug": "gandhi-mandapam",
        "category": "cultural",
        "location": "POINT(80.2370 13.0080)",
        "description": "Memorial complex dedicated to Mahatma Gandhi.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "06:00-20:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 60,
        "popularity_score": 73,
    },
    {
        "name": "St Thomas Mount",
        "slug": "st-thomas-mount",
        "category": "cultural",
        "location": "POINT(80.1937 12.9958)",
        "description": "Historic hilltop church and viewpoint.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "06:00-20:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 75,
        "popularity_score": 83,
    },
    {
        "name": "Madras War Cemetery",
        "slug": "madras-war-cemetery",
        "category": "cultural",
        "location": "POINT(80.1852 13.0135)",
        "description": "Commonwealth war cemetery and historical site.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "08:00-17:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 45,
        "popularity_score": 65,
    },

    # Food / Restaurant areas
    {
        "name": "Mylapore Food Street",
        "slug": "mylapore-food-street",
        "category": "restaurant",
        "location": "POINT(80.2688 13.0345)",
        "description": "Traditional food area around the Mylapore temple district.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "08:00-22:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 90,
        "popularity_score": 82,
    },
    {
        "name": "Marina Beach Food Zone",
        "slug": "marina-beach-food-zone",
        "category": "restaurant",
        "location": "POINT(80.2810 13.0490)",
        "description": "Popular beachside food and snack area.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "16:00-22:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 60,
        "popularity_score": 86,
    },
    {
        "name": "Besant Nagar Food Street",
        "slug": "besant-nagar-food-street",
        "category": "restaurant",
        "location": "POINT(80.2695 12.9990)",
        "description": "Popular dining area near Elliot's Beach.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "10:00-23:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 90,
        "popularity_score": 84,
    },
    {
        "name": "Koyambedu Market",
        "slug": "koyambedu-market",
        "category": "shopping",
        "location": "POINT(80.1955 13.0694)",
        "description": "Large wholesale market complex and commercial landmark.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "05:00-22:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 120,
        "popularity_score": 74,
    },
    {
        "name": "Kalakshetra Foundation",
        "slug": "kalakshetra-foundation",
        "category": "cultural",
        "location": "POINT(80.2598 12.9940)",
        "description": "Cultural institution dedicated to Indian classical arts and traditions.",
        "city": "Chennai",
        "state_province": "Tamil Nadu",
        "country": "India",
        "opening_hours": "09:00-17:00",
        "entry_fee": 0,
        "entry_fee_currency": "INR",
        "average_visit_duration_minutes": 120,
        "popularity_score": 78,
    },
]


def seed():
    db = SessionLocal()
    added = 0
    skipped = 0

    try:
        for data in DESTINATIONS:
            slug = data["slug"]

            existing = (
                db.query(Destination)
                .filter(Destination.slug == slug)
                .first()
            )

            if existing:
                skipped += 1
                continue

            # Don't mutate the original DESTINATIONS data
            destination_data = data.copy()

            # Convert the category string to the SQLAlchemy enum
            destination_data["category"] = DestinationCategory(
                destination_data["category"]
            )

            # Extract location separately
            location = destination_data.pop("location")

            destination = Destination(
                **destination_data,
                location=location,
            )

            db.add(destination)
            added += 1

        db.commit()

        count = db.query(Destination).count()

        print(f"Added: {added}")
        print(f"Skipped: {skipped}")
        print(f"Total destinations: {count}")

    except Exception:
        db.rollback()
        raise

    finally:
        db.close()


if __name__ == "__main__":
    seed()
